---
antora:
  name: modules
  dir: www
  modules:
    - name: index
      label: "Introduction"
      solveButton: false
    - name: module-01
      label: "examine-ansible-playbook"
      solveButton: false
    - name: module-02
      label: "ansible-resource-playbook"
      solveButton: true
    - name: module-03
      label: "execute-resource-playbook"
      solveButton: true
    - name: module-04
      label: "gathered-parameter"
      solveButton: false
tabs:
  - name: "code-server"
    url: https://vscode-${guid}.${domain}/?folder=/home/rhel
    external: false
  - name: "TERMINAL"
    url: /wetty_vscode
