---
containers: []
virtualmachines:
  - name: "vscode"
    image: "devtools-ansible"
    memory: "8G"
    cores: 2
    image_size: "20Gi"
    disk_type: "scsi"
    bootloader: "efi"
    tags:
      - key: "AnsibleGroup"
        value: "isolated"
    networks:
      - default
    services:
      - name: vscode-8080
        ports:
          - port: 8080
            protocol: TCP
            targetPort: 8080
            name: vscode
    routes:
      - name: vscode-8080
        host: vscode
        service: vscode-8080
        targetPort: 8080
        tls: true
        tls_termination: Edge
    userdata: |-
      #cloud-config
      user: rhel
      password: ansible123!
      chpasswd: { expire: False }
      runcmd:
        - echo "PasswordAuthentication yes" > /etc/ssh/sshd_config.d/50-cloud-init.conf
        - systemctl reload sshd

  - name: "cisco"
    image: "c8000v-rhdp-8g"
    memory: "8G"
    cores: "4"
    image_size: "10Gi"
    tags:
      - key: "AnsibleGroup"
        value: "isolated"
    networks:
      - default
    cdroms:
      - metadata:
          name: "cisco-config"
        spec:
          source:
            pvc:
              name: "ans-bu-cisco-rhdp-config"
              namespace: cnv-images
          pvc:
            accessModes:
            - ReadWriteMany
            volumeMode: Block
            resources:
              requests:
                storage: "20Mi"
